application: shlugchat
version: 3
runtime: python
api_version: 1

handlers:
- url: /sendmsg
  script: sendmsg.py
  login: admin
- url: /chatbridge
  script: chatbridge_entry.py
- url: /.*
  script: xmpp.py


inbound_services:
- xmpp_message
